services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "2022"
      RAM_SIZE: "12G"
      CPU_CORES: "8"
      DISK_SIZE: "380G"
      USERNAME: "MasR"
      PASSWORD: "adminr"
      REGION: "id_ID"
      KEYBOARD: "en_US"
      EDITION: "core"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 8006:8006/tcp
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
